name: Kamal Deploy

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instala dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl docker.io sshpass

      - name: Configura chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H goals.pedrorl.online >> ~/.ssh/known_hosts

      - name: Instala Kamal
        run: |
          gem install kamal

      - name: Kamal setup
        run: kamal setup

      - name: Kamal deploy
        run: kamal deploy
